[package]
name = "nabla_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
nabla_frontend = { path = "../nabla_frontend" }
serde = "1.0.193"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
toml = "0.8.8"
xml-builder = "0.5.2"
